TOMCAT_HOME: /usr/local/tomcat
CATALINA_HOME: /usr/local/tomcat
CATALINA_BASE: /data/tomcats/{{ site }}
CATALINA_LOGBASE: /data/tomcats/{{ site }}/logs
PROJECT_BASE: /data/projects/{{ site }}
JAVA_HOME: {{ JAVA_HOME | default(/usr/lib/jvm/java-7-openjdk-amd64) }}
JAVA_OPTS: '-server -Xms{{ jvm | default(128) }}m -Xmx{{ jvm | default(128) }}m -XX:PermSize=512M -XX:MaxNewSize=512m -XX:MaxPermSize=1024m'
TOMCAT_USER: www
