---
- set_fact:
   Pool: "{{ site }}"
   site_path: "{{ physical_path }}\\{{ site }}"
   log_path: "{{ logs_path }}\\{{ site }}"
  when: (app is undefined)

- set_fact:
   Pool: "{{ site }}.{{ app | replace('/','.') }}"
   site_path1: "{{ physical_path }}\\{{ site }}\\{{ app | replace('/','\\]') }}"
   log_path: "{{ logs_path }}\\{{  site }}\\{{ app }}"
  when: (app is defined)

- set_fact:
   site_path: "{{ site_path1 | replace(']','') }}"
  when: (app is defined)

- set_fact:
   ip_listen: ''
  when: (ip is defined)

- set_fact:
   ip_listen: "{{ ansible_ip_addresses[0] }}"
  when: (ip is undefined)
