---
- name: Local | 项目 "{{ site_path }}" 检出
  local_action: |
    shell \
      {% if revision_old.stdout == "" %}
         svn co {{ svn_info.url }}/{{ site_path }} {{ svn_temp }}/{{ site_path }} --username {{ svn_info.user }} --password {{ svn_info.pass }} --force --no-auth-cache --non-interactive --trust-server-cert
      {% else %}
         svn up -r {{ revision }} {{ svn_temp }}/{{ site_path }} --username {{ svn_info.user }} --password {{ svn_info.pass }} --force --no-auth-cache --non-interactive --trust-server-cert
      {% endif %} 
    > {{ rsync.log_path }}
  run_once: true
